#!/bin/bash
# send email with the latest changes from all repositories.
# Ivan Dimitrov https://github.com/dobber
# for Ancient Media Ltd.

mailer="/usr/bin/bsd-mailx"
repodir="/home/git/repositories/"
from="From: root@${HOSTNAME}" # $HOSTNAME must be FQDN
email="your@email.addr"
template="A list of changes in all repositories for the last week"
subject="Weekly list of git changes"
period="1.week"
web="http://gitlab.bastun.net/"

###### DO NOT EDIT BELOW THIS LINE ########
prettyf="%ae
<tr>
	<td width=\"150\">
		<a class=\"commit-author-link\" href=\"${web}/u/USER/\">
			<span class=\"commit-author-name\">%an</span>
			<img class=\"avatar s24\" width=\"24\" src=\"https://secure.gravatar.com/avatar/HASH?s=24&d=mm\" alt=\"\">
		</a>
	</td>
	<td valign=\"top\">
		<a href=\"${web}/USER/REPO/commit/%H\">%s</a>
	</td>
</tr>"
index=0
debug=0

function generate_email {
	user=$1
	repo=$2
	hash=$3
	message=$4

	message=`echo "${message}" | sed -e s/USER/${user}/g`
	message=`echo "${message}" | sed -e s/REPO/${repo}/g`
	message=`echo "${message}" | sed -e s/HASH/${hash}/g`
	if [ $index -eq 0 ] ; then
		mail="<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
<html xmlns=\"http://www.w3.org/1999/xhtml\">
<head>
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />
<title>$subject</title>
<style type=\"text/css\">
body {
	margin: 0px;
	padding: 0px;
	text-align: center;
	width: 100%;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 14px;
}
.avatar {
	border: 1px solid #DDDDDD;
	float: left;
	margin-right: 12px;
	padding: 1px;
	width: 40px;
}
img {
	border: 0 none;
	height: auto;
	max-width: 100%;
	vertical-align: middle;
}
.avatar.s24 {
	height: 24px;
	margin-right: 8px;
	width: 24px;
}
.commit-author-name {
	color: #000;
	font-weight: bold;
	line-height:24px;
}
.header {
	background: linear-gradient(#EEEEEE 6.6%, #DFDFDF) repeat scroll 0 0 #EEEEEE;
	border-bottom: 1px solid #CCCCCC;
}
tr {
	background: #F7F7F7;
}
td {
	text-align: left;
	line-height:24px;
}
a, a:hover {
	color: #DA241D;
	text-decoration: none;
}
h1 {
	font-size:40px;
	width:670px;
}
</style>
</head>

<body>
<table width=\"700\" border=\"0\" cellspacing=\"2\" cellpadding=\"5\" align=\"center\">
  <tr align=\"center\">
        <th class=\"header\" colspan=\"2\" bgcolor=\"#FFFFFF\" align=\"center\">
		<h1>
			<img src=\"http://ancientmedia.com/logo.jpg\" width=\"64\" />
			$subject
		</h1>
	</td>
  </tr>
  <tr>
	<td colspan=\"2\" bgcolor=\"#FFFFFF\" align=\"center\">
		$template
	</td>
  </tr>

<br /><br />"
		index=1
	fi

	mail="$mail
	<tr>
		<td class=\"header\" colspan=\"2\" align=\"left\" height=\"46\" style=\"font-size:24px; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; padding:5px;\">
			<a href=\"${web}/${user}/${repo}/commits/master\">${repo}</a>
		</td>
	</tr>
${message}
"
}

function just_print {
	echo "  ::      $1 ::"
	echo "$2"
	echo "=============================================="
}

case "$1" in
	dry-run)
		debug=1
		prettyf="%an <%ae> - %s"
		;;
	help)
		echo $"Usage: $0 {help|dry-run|no-options}"
		exit 0
		;;
	no-options)
		echo "Actualy you can just run \`$0\` with no options and it will work too!"
		debug=0;
		;;
	*)
		debug=0
esac

if [ ! -d ${repodir} ] ; then
	echo "Repo dir does not exist"
	exit 0
fi

for user in `ls ${repodir}/` ; do
	for repo in `ls ${repodir}/${user}/` ; do
		out=`git --git-dir=${repodir}/${user}/${repo} log --since=${period} --pretty="${prettyf}"`
		if [ -n "$out" ] ; then
			cmail=`echo $out | awk '{print $1}'`
			out=`echo "$out" | sed s/$cmail//`
			hash=`echo "$cmail" | tr -d '\n' | md5sum | awk '{print $1}'`
			reponame=`echo ${repo} | cut -f 1 -d.`
			if [ $debug -eq 0 ] ; then
				generate_email "${user}" "${reponame}" "${hash}" "$out"
			else
				just_print "${reponame}" "${out}"
			fi
		fi
		unset out
	done
done

if [ $debug -eq 0 ] ; then
	mail="$mail</table><br /><br />
	<p><h5>
		<a href=\"https://github.com/dobber/git-notify\">Generated by git-notify</a>
	</h5></p>
</body></html>"
	echo "${mail}" | ${mailer} -a "${from}" -a "MIME-Version: 1.0" -a "Content-Type: text/html;charset=utf-8" -s "${subject}" "${email}"
fi
